version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/vysma_design"
    versioning-strategy: increase # https://github.com/dependabot/dependabot-core/issues/6446
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/vysma_design/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_vysma_design"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_vysma_design/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/vysma_design/native"
    schedule:
      interval: weekly
