[package]
name = "vysma_design_layout"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.78.0"

[dependencies]
flutter_rust_bridge = "1.78.0"
anyhow = "1.0.*"
hcl-rs = "0.15.0"
serde = "1.0.*"
serde_json = "1.0.*"
lazy_static = "1.*"
parking_lot = "0.12.*"
uuid = { version = "1.3.3", features = ["v4"] }
