name: flutter_vysma_design
description: Flutter Vysma Design Library 
version: 0.0.1
homepage: https://github.com/tranthaian3591/ffi_plugin_test
repository: https://github.com/tranthaian3591/ffi_plugin_test
issue_tracker: https://github.com/tranthaian3591/ffi_plugin_test/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  path: ^1.8.2
  path_provider: ^2.0.11
  vysma_design: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
