name: vysma_design
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/tranthaian3591/ffi_plugin_test

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.2
  flutter_rust_bridge: 1.78.0
  freezed_annotation: ^2.2.0
  meta: ^1.8.0

  # TODO https://github.com/fzyzcjy/flutter_rust_bridge/issues/1147
  uuid: any

dev_dependencies:
  analyzer: ^6.0.0
  build_runner: ^2.3.2
  ffigen: ^8.0.2
  freezed: ^2.2.1
  test: ^1.22.0

