name: flutter_vysma_design_example
description: flutter_vysma_design example application
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # You can replace these with the latest versions
  flutter_vysma_design: ^0.0.7+3
  vysma_design: ^0.2.0

  # These two are needed for the example; they are not required by vysma_design
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # Copied from https://github.com/glin/reactable/blob/d8310ca34e1055d490c0a6b5af5fa0c7f291a709/vignettes/popular-movies/tmdb_movies.json
    - assets/tmdb_movies.json
